### ISSUE TITLE
Course survey tracking issue

### ISSUE THREAD

**Issue by jameslzhu** [compserv/hkn-rails#204]
Related: #202 #181 #199 

- [x] Fix BOM (#202)
- [x] Fix "Response Rate" column error (#202)
- [ ] Allow more departments (IEOR)
- [ ] (Optional) Remove spurious reviews with non-existant data (0, N/A, etc.) or for non-existant classes (?)
